BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `time_stamps` (
	`column_name`	TEXT UNIQUE,
	`time_stamp`	REAL
);
INSERT INTO `time_stamps` (column_name,time_stamp) VALUES 
('min_0',NULL),
('min_5',NULL),
 ('min_10',NULL),
 ('min_15',NULL),
 ('min_20',NULL),
 ('min_25',NULL),
 ('min_30',NULL),
 ('min_35',NULL),
 ('min_40',NULL),
 ('min_45',NULL),
 ('min_50',NULL),
 ('min_55',NULL),
 ('hr_1',NULL),
 ('hr_2',NULL),
 ('hr_3',NULL),
 ('hr_4',NULL),
 ('hr_5',NULL),
 ('hr_6',NULL),
 ('hr_7',NULL),
 ('hr_8',NULL),
 ('hr_9',NULL),
 ('hr_10',NULL),
 ('hr_11',NULL),
 ('hr_12',NULL),
 ('hr_13',NULL),
 ('hr_14',NULL),
 ('hr_15',NULL),
 ('hr_16',NULL),
 ('hr_17',NULL),
 ('hr_18',NULL),
 ('hr_19',NULL),
 ('hr_20',NULL),
 ('hr_21',NULL),
 ('hr_22',NULL),
 ('hr_23',NULL),
 ('hr_24',NULL);
CREATE TABLE IF NOT EXISTS `last_update_info` (
	`_id`	TEXT,
	`last_updated_min_col`	INTEGER,
	`last_update_hr_col`	INTEGER,
	`last_update_time`	TEXT,
	`number_of_coins`	INTEGER
);
CREATE TABLE IF NOT EXISTS `coin_history` (
	`coin_key`	TEXT UNIQUE,
	`min_0`	INTEGER,
	`min_5`	INTEGER,
	`min_10`	INTEGER,
	`min_15`	INTEGER,
	`min_20`	INTEGER,
	`min_25`	INTEGER,
	`min_30`	INTEGER,
	`min_35`	INTEGER,
	`min_40`	INTEGER,
	`min_45`	INTEGER,
	`min_50`	INTEGER,
	`min_55`	INTEGER,
	`hr_1`	INTEGER,
	`hr_2`	INTEGER,
	`hr_3`	INTEGER,
	`hr_4`	INTEGER,
	`hr_5`	INTEGER,
	`hr_6`	INTEGER,
	`hr_7`	INTEGER,
	`hr_8`	INTEGER,
	`hr_9`	INTEGER,
	`hr_10`	INTEGER,
	`hr_11`	INTEGER,
	`hr_12`	INTEGER,
	`hr_13`	INTEGER,
	`hr_14`	INTEGER,
	`hr_15`	INTEGER,
	`hr_16`	INTEGER,
	`hr_17`	INTEGER,
	`hr_18`	INTEGER,
	`hr_19`	INTEGER,
	`hr_20`	INTEGER,
	`hr_21`	INTEGER,
	`hr_22`	INTEGER,
	`hr_23`	INTEGER,
	`hr_24`	INTEGER,
	PRIMARY KEY(`coin_key`)
);
COMMIT;
