CFLAGS=-Wall -g -I/home/minol/.local/include -I/home/minol/.local/include/libmongoc-1.0 -I/home/minol/.local/include/libbson-1.0
LDFLAGS=-L/home/minol/.local/lib -lmongoc-1.0 -lssl -lcrypto -lrt -lresolv -lz -lbson-1.0 -ljansson -lcurl

TARGETS=bson1

clean:
	rm -rf *.o $(TARGETS)
